### ISSUE TITLE
Edge ids should be strings

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#15]
When we create new edges, we're returning their kg_id as integers, which is out of spec.

Instead, they should be strings.

**Comment by PhillipsOwen** [comment]
i added code to insure that the result of the new edge id hash is coerced into a string. 
fix is in Phil_AC branch.

**Comment by cbizon** [comment]
Please add a test around this issue and then close / merge

**Comment by PhillipsOwen** [comment]
fixed in a4a494d

**Comment by PhillipsOwen** [comment]
new tests passed.
