### ISSUE TITLE
graph version is returning named_things w/o labels

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#16]
New nodes added to the answer only have typed named_thing and don't have labels.  We could run through nodenorm, but these properties should also be available from the graph...

**Comment by cbizon** [comment]
As an example, once graph coalescence has run in the AnswerCoalesce notebook, I do this:
`print( graph_result['knowledge_graph']['nodes'])`

Most of the nodes are fine, but there are several that are not:
```
{'id': 'CHEBI:10545', 'type': 'named_thing'}, {'id': 'CHEBI:24431', 'type': 'named_thing'}, {'id': 'CHEBI:25585', 'type': 'named_thing'}, {'id': 'CHEBI:27594', 'type': 'named_thing'}, {'id': 'CHEBI:33250', 'type': 'named_thing'}, {'id': 'CHEBI:33306', 'type': 'named_thing'}, {'id': 'CHEBI:33318', 'type': 'named_thing'}, {'id': 'CHEBI:33560', 'type': 'named_thing'}, {'id': 'CHEBI:22221', 'type': 'named_thing'}, {'id': 'CHEBI:23004', 'type': 'named_thing'}, {'id': 'CHEBI:27207', 'type': 'named_thing'}, {'id': 'CHEBI:37838', 'type': 'named_thing'}, {'id': 'MEDDRA:10013710', 'type': 'named_thing'}, {'id': 'MEDDRA:10029328', 'type': 'named_thing'}, {'id': 'MONDO:0008889', 'type': 'named_thing'}, {'id': 'CHEBI:23019', 'type': 'named_thing'}, {'id': 'CHEBI:33246', 'type': 'named_thing'}, {'id': 'CHEBI:46629', 'type': 'named_thing'}, {'id': 'CHEBI:51422', 'type': 'named_thing'}, {'id': 'CHEBI:51446', 'type': 'named_thing'}, {'id': 'CHEBI:23367', 'type': 'named_thing'}, {'id': 'CHEBI:24835', 'type': 'named_thing'}, {'id': 'CHEBI:29235', 'type': 'named_thing'}, {'id': 'CHEBI:33249', 'type': 'named_thing'}, {'id': 'CHEBI:33559', 'type': 'named_thing'}, {'id': 'CHEBI:37527', 'type': 'named_thing'}, {'id': 'CHEBI:43176', 'type': 'named_thing'}, {'id': 'CHEBI:46883', 'type': 'named_thing'}, {'id': 'CHEBI:51447', 'type': 'named_thing'}, {'id': 'CHEBI:24433', 'type': 'named_thing'}, {'id': 'CHEBI:24473', 'type': 'named_thing'}, {'id': 'CHEBI:29311', 'type': 'named_thing'}, {'id': 'CHEBI:25555', 'type': 'named_thing'}, {'id': 'CHEBI:33300', 'type': 'named_thing'}, {'id': 'CHEBI:25805', 'type': 'named_thing'}, {'id': 'CHEBI:33247', 'type': 'named_thing'}, {'id': 'CHEBI:26833', 'type': 'named_thing'}
```

I put some of the chebis into node normalization and they came back fine.  This might be a version problem though.  Perhaps these didn't get properly normalized in the robokop grpah or some derivative that the service is using?

**Comment by PhillipsOwen** [comment]
are we talking a redo of the entire DB or just a targeted normalization sweep of the insufficient ones?

**Comment by cbizon** [comment]
First, we need to understand why this is happening, then we can make a decision on how to fix it.  In other words, I can't answer your question, because I don't know what/where the problem actually is.

**Comment by PhillipsOwen** [comment]
do you know when this was loaded? perhaps there is an old graph backup we can restore to verify.

**Comment by cbizon** [comment]
Sorry, I don't know what you're referring to.   There are at least 3 databases in play - the robokop graph, the sqlite dbs, and the redis backing nodenormalization.  I don't know which, if any, are the reason for the bug.

The first thing to do, I think, is write a simple test verifying the behavior.

**Comment by cbizon** [comment]
This is also true of the ontology version.

**Comment by cbizon** [comment]
I think that the right idea here is to use node normalization on our output graphs before sending them back.  We will soon have a TRAPI nodenorm interface which will simplify this, so once that's done, we'll implement.
