### ISSUE TITLE
Rerank answers

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#30]
After coalescing, rerank answers rather than just picking the best rank from the coalesced set.

**Comment by cbizon** [comment]
I think that we should probably not rerank within the service, but we might imagine different workflows using ranking.  Maybe answers should not be ranked until after they are coalesced.  

Another option will be adding edge weights to new edges based on the coalsecent p-values.   Should this happen in the normal edge weighter?

**Comment by cbizon** [comment]
@patrickkwang curious if you have thoughts about whether all edge weighting should happen in one place or not.  i.e. should our current weighter become an umbrella for different weighting schemes, or should it be a specific paper->weight mechanism, and then there is a different one for e.g. coalscent edges on p-value, and another for chemical/gene measurements.

I guess that if they work independently then we need a more careful scheme for adding different weights to an edge and the ranker will have to pick and choose from among them.

**Comment by patrickkwang** [comment]
We'll need a way of storing diverse types of quantitative metadata on edges, for sure. We'll also need procedures for mapping them into a unified representation and/or for directly computing the aggregate result score with knowledge of the different weighting schemes.
