### ISSUE TITLE
Provenance on GC edges

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#47]
This is an edge added by GC:
```
{'subject': 'NCBIGene:1576', 'object': 'PUBCHEM.COMPOUND:68911', 'predicate': 'biolink:increases_degradation_of', 'attributes': [{'type': 'EDAM:data_0006', 'value': 1, 'name': 'weight'}]}
```

Note that there is no provenance on this edge.  We need to add that information to the AC redis somehow.

**Comment by mmersmann** [comment]
Duplicate of "add provenance to answer coalescer". Closing.
