### ISSUE TITLE
No Graph coalescence?

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#54]
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:ChemicalSubstance"
                    ]
                },
                "n1": {
                    "ids": [
                        "HGNC:6284"
                    ],
                    "categories": [
                        "biolink:Gene"
                    ]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

Running the above query through aragorn, we get a bunch of results.  They give all kinds of property coalescence, but no graph coalescence.  That seems incorrect, but may be correct?  need to double check.

**Comment by PhillipsOwen** [comment]
this issue not limited to the query you post above.

the redis cache is empty. i will start reloading it now.

**Comment by cbizon** [comment]
Is this another example where we need to update the way kubernetes is handling this container?
Whatever that option that Yaphet was mentioning?

**Comment by PhillipsOwen** [comment]
yes i believe it is. if the persistent volume remained after a new deployment this wouldnt happen.

**Comment by PhillipsOwen** [comment]
issue resolved with the loading of the redis cache. closing the ticket.
