### ISSUE TITLE
Make output properties TRAPI compliant

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#55]
Right now the p-values and stuff returned from AC I think are not in full trapi compliance?

```
{'node_bindings': {'n1': [{'id': 'NCBIGene:3778'}],
  'n0': [{'id': 'PUBCHEM.COMPOUND:5994',
    'coalescence_method': 'property_enrichment',
    'p_values': [5.515487725071365e-06],
    'properties': ['molecule_type:Small molecule']},
```

**Comment by PhillipsOwen** [comment]
i will correct.

**Comment by PhillipsOwen** [comment]
The TRAPI 1.1 spec does not specify the "attributes" property for result node bindings. the spec is generous is generous in this case and will allow basically anything you put in there.

however, node normalization currently fails when a non-hashable type (in this case the attributes dict) is encountered while merging node data. in addition, node norm does not normalize any curie values in the results. Node normalization will have to be modified if this change is implemented.

it is not known at this time if any other downstream components would have an issue here as well.

**Comment by cbizon** [comment]
I think it makes sense to robustify nn to handle properties of this type, and to update the binding properties to match other trapi properties, even if it is not required.

**Comment by PhillipsOwen** [comment]
understood, thanks!

**Comment by mmersmann** [comment]
What we're doing is TRAPI compliant, but we would like to make TRAPI require us to include standards around this part of the message. Phil is creating an issue in the TRAPI repo to add standards around attributes in this part of the message.
