### ISSUE TITLE
Investigate coalescence for query

### ISSUE THREAD

**Issue by PhillipsOwen** [ranking-agent/AnswerCoalesce#60]
I have this query:

{
    "message": {
        "query_graph": {
            "nodes": {
                "n1": {
                    "ids": ["MONDO:0004979"],
                    "categories": ["biolink:Disease"]
                },
                "n0": {
                    "categories": ["biolink:ChemicalSubstance"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats"]
                }
            }
        }
    }
}

I would expect it to do some answer coalescing.  It returns ~200 results, but none of them are coalesced.  Can you just double check that something odd is not going on?

**Comment by mmersmann** [comment]
Cluster resolution → deploy 1.1.2 version of NN w/o updating cache → deploy 1.1.2 version of AC → deploy 1.1.2 version of ARAGORN (possibly)

**Comment by PhillipsOwen** [comment]
As of today the Cluster memory upgrade is on hold until the correct memory is received from the vendor.

**Comment by mmersmann** [comment]
Phil to review Strider output for this query, to determine whether this is related to RTX issue.

**Comment by PhillipsOwen** [comment]
here is the strider output from the input above.

[strider_out_issue_60.json.txt](https://github.com/ranking-agent/AnswerCoalesce/files/6765766/strider_out_issue_60.json.txt)

**Comment by PhillipsOwen** [comment]
these are the 3 AC outputs (ontology, graph and property) for the input above. it would appear that the graph output is running into a lookup error that halted further processing.

[ac_out_issue_60.zip](https://github.com/ranking-agent/AnswerCoalesce/files/6785710/ac_out_issue_60.zip)

**Comment by mmersmann** [comment]
One phase of AC that runs into issues where line count doesn't come back because predicate not in database associated with that particular curie.
