### ISSUE TITLE
TRAPI TIMELINE: KPs complete v1.2 implementations

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/AnswerCoalesce#72]
**Due Date:** August 18
**Note:** 1.1 and 1.2 should run in parallel until we’re ready to shut off 1.1
[TRAPI 1.1 to 1.2 Change Log](https://github.com/NCATSTranslator/ReasonerAPI/pull/277/files).
[ReasonerAPI Reference Ticket](https://github.com/NCATSTranslator/ReasonerAPI/issues/271)

**Comment by PhillipsOwen** [comment]
just an FYI...
 - helm charts have been created to deploy a side-by-side 1.1 and 1.2 deploy.
 - currently waiting on a answer coalesce trapi 1.2 compliant docker image to deploy.

**Comment by mmersmann** [comment]
AC 1.2 is pushed. Node Norm 1.2 updates will make this complete. Expected today.

**Comment by PhillipsOwen** [comment]
node normalization, aragorn, answer coalesce and aragorn-ranker /1.2 instances have been deployed.

currently experiencing issues with NN that are being addressed now.

**Comment by richakanwar13** [comment]
As per meeting on 9/17, this can be closed.
