### ISSUE TITLE
Over-agressive AC

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/AnswerCoalesce#77]
See e.g. https://arax.ncats.io/?source=ARS&id=a7642344-b95e-4c1a-a278-84af1e7cf75b

This is a query where we return a few genes.    AC is saying that they are subclasses of things like ChemicalEntity and stuff out of CHEBI

**Comment by cbizon** [comment]
These are conflated gene/protein entities, so subclass of chemical entity is fine.  But 2 arbitrary things that are chemical entities doesn't seem like anything.  Maybe AC is getting confused and thinking that these should be treated as genes...

**Comment by cbizon** [comment]
Same here with straight chemicals 
https://arax.ncats.io/?source=ARS&id=8ec7d8fd-684c-482f-9e19-68bec7f8b387

**Comment by richakanwar13** [comment]
Per meeting on 9/24, can be closed.
